Datamodule:
  patch_size: 256
  eval_patches_root: /home/alalbiol/Data/mamo/DDSM_eval_patches/eval_patches_256
  convert_to_rgb: False
  batch_size: 128

Logger:
  name: model_nikulin_256
  save_dir: /tmp/logs/model_nikulin_256_topk


LightningModule:
  model_name: nikulin
  n_hard_mining: 64

Callbacks:
  ModelCheckpoint:
    dirpath: /tmp/logs/model_nikulin_256_topk
