Datamodule:
  patch_size: 224
  convert_to_rgb: False
  batch_size: 128

Logger:
  name: model_nikulin_224
  save_dir: /tmp/logs/model_nikulin_224_topk


LightningModule:
  model_name: nikulin
  n_hard_mining: 64

Callbacks:
  ModelCheckpoint:
    dirpath: /tmp/logs/model_nikulin_224_topk
