_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": validation batch._type
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.size
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.path
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.sha256
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.path
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.width
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.height
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions.filenames
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions.format
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.sha256
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.size
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch.format
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions.count
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions.width
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions.height
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_precisions
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.width
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.height
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation batch.format
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training batch._type
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_predictions._type
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_map
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_recall
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 80
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 80
                - 103
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.5
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
