# Fase IV-A | Nikulin | LR = 1e-4
# Hereda de base_config.yaml

Datamodule:
  patch_size: 224
  convert_to_rgb: False
  normalize_input: True

Logger:
  name: E04_nikulin_LR1e-4

LightningModule:
  model_name: nikulin
  learning_rate: 0.0001

Callbacks:
  LearningRateMonitor:
    logging_interval: 'epoch'
  ModelCheckpoint:
    monitor: val_auroc
    mode: max
    save_top_k: 1
    dirpath: /home/eblanov/tmp/logs/E04_N2_nikulin_LR1e-4
    filename: best_{epoch}-{val_auroc:.4f}
    verbose: True