# Fase IV-A | Nikulin | LR = 1e-3
# Hereda de base_config.yaml

Datamodule:
  patch_size: 224
  normalize_input: True
  train_set:
    convert_to_rgb: False
  val_set:
    convert_to_rgb: False

Logger:
  name: E04_nikulin_LR1e-3

Trainer:
  max_epochs: 500

LightningModule:
  model_name: nikulin
  num_classes: 5
  num_classes: 5
  num_classes: 5
  learning_rate: 0.001

Callbacks:
  LearningRateMonitor:
    logging_interval: 'epoch'
  ModelCheckpoint:
    monitor: val_auroc
    mode: max
    save_top_k: 3
    dirpath: /home/eblanov/tmp/logs/E04_N1_nikulin_LR1e-3
    filename: best_{epoch}-{val_auroc:.4f}
    verbose: True
