# Fase IV-A | ResNet50 | LR = 1e-4
# Hereda de base_config.yaml

Datamodule:
  patch_size: 224

Logger:
  name: E04_resnet50_LR1e-4

LightningModule:
  model_name: resnet50
  learning_rate: 0.0001

Callbacks:
  LearningRateMonitor:
    logging_interval: 'epoch'
  ModelCheckpoint:
    monitor: val_auroc
    mode: max
    save_top_k: 3
    dirpath: /home/eblanov/tmp/logs/E04_R2_resnet50_LR1e4
    filename: best_{epoch}-{val_auroc:.4f}
    verbose: True