General:
  source_root: /home/eblanov/proymam2/Mammography/elsa
  gpu_type: "RTX 5090"

Phase4:
  patch_config: config_files/swin/swin_224_LR1e-4.yaml

Datamodule:
  ddsm_root:          /home/Data/mamo/DDSM_png_16bit_1120x896
  val_csv:            resources/ddsm/DDSM_test.csv
  ddsm_annotations:   resources/ddsm/ddsm_annotations_16bits_1120_896.json.gz
  patch_size:         224
  stride:             112
  convert_to_rgb:     True
  normalize_input:    True
  mini_batch_size:    128
  num_workers:        8
  subset_size:        null

Logger:
  type: wandb
  project: ddsm_image_fusion
  name: E05_fusion_stride112
  save_dir: /home/eblanov/tmp/logs/E05_fusion_stride112
